"""Embed the policy corpus and store it in postgres.

Loads the embedding model once (it's the expensive part), turns each chunk's
text into a 384-dim vector, and upserts it into policy_chunks. The tsvector
column is generated by postgres automatically, so we only supply the body and
the embedding. Re-running replaces existing rows (idempotent).

    python -m rag.ingest
"""
from __future__ import annotations

from db import repository as repo
from rag import corpus as corpus_module
from rag.embedding import embed_one

UPSERT = """
INSERT INTO policy_chunks (chunk_id, code, section, title, body, embedding)
VALUES (%s, %s, %s, %s, %s, %s)
ON CONFLICT (chunk_id) DO UPDATE SET
    code = EXCLUDED.code, section = EXCLUDED.section, title = EXCLUDED.title,
    body = EXCLUDED.body, embedding = EXCLUDED.embedding
"""


def ingest(url: str | None = None) -> int:
    chunks = corpus_module.build_corpus()
    with repo.connect(url) as conn:
        with conn.cursor() as cur:
            for c in chunks:
                vector = embed_one(c["text"])
                cur.execute(UPSERT, (c["chunk_id"], c["code"], c["section"],
                                     c["title"], c["text"], vector))
        conn.commit()
    return len(chunks)


if __name__ == "__main__":
    n = ingest()
    print(f"Ingested {n} policy chunks into policy_chunks.")
